const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth.cjs');
const User = require('../models/User.cjs');
const { v4: uuidv4 } = require('uuid'); // For generating unique IDs

// @route   POST api/invite/generate
// @desc    Generate a unique invite link/code
// @access  Private
router.post('/generate', auth, async (req, res) => {
  try {
    const user = await User.findById(req.user.id);
    if (!user) {
      return res.status(404).json({ msg: 'User not found' });
    }

    const inviteCode = uuidv4();
    // In a real application, you might save this inviteCode to the user's document
    // or a dedicated Invite model, potentially with an expiry and usage count.
    // For now, we'll just generate and return it.

    // Example of saving to user (requires adding 'invites' array to User model)
    /*
    user.invites.push({
      code: inviteCode,
      generatedAt: new Date(),
      status: 'active',
      uses: 0
    });
    await user.save();
    */

    const inviteLink = `${process.env.FRONTEND_BASE_URL}/invite?code=${inviteCode}`; // Assuming a frontend invite page

    res.json({ inviteCode, inviteLink });
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

// @route   POST api/invite/email
// @desc    Send invitation via email
// @access  Private
router.post('/email', auth, async (req, res) => {
  const { email, inviteLink } = req.body; // inviteLink should be generated by frontend or previous step

  const nodemailer = require('nodemailer');
  let transporter = nodemailer.createTransport({
      service: process.env.EMAIL_SERVICE,
      auth: {
          user: process.env.EMAIL_USER,
          pass: process.env.EMAIL_PASS
      }
  });

  let mailOptions = {
      from: process.env.EMAIL_USER,
      to: email,
      subject: 'You\'re invited to Local Hub Replicator!', // App name
      html: `<p>You have been invited to join Local Hub Replicator! Click <a href="${inviteLink}">here</a> to join.</p>`
  };

  try {
      await transporter.sendMail(mailOptions);
      res.json({ msg: 'Invitation email sent successfully' });
  } catch (error) {
      console.error('Email send error:', error);
      res.status(500).json({ msg: 'Failed to send invitation email' });
  }
});

// For tracking sent invites, you would need to:
// 1. Add an 'invitesSent' array to the User model, storing objects like { code: String, email: String, status: String, sentAt: Date }
// 2. Update the 'POST /generate' and 'POST /email' routes to record these.
// 3. Add a GET route '/api/invite/sent' to retrieve them.

module.exports = router;
